baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'triple-hyde'

[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 1
    url = "/portfolio/"
